### ISSUE TITLE
Update README: clarify what this repository is

### ISSUE THREAD

**Issue by arielelkin** [Zewo/HTTP#24]
I came here from http://docs.zewo.io/ and even though I know this repo is hosting a module that i can use for server-side development, I can't figure out at a glance what it is and how to use it. 

The readme should include information about what this code does and how to use it. 

See:
http://stackoverflow.com/questions/2304863/how-to-write-a-good-readme

**Comment by paulofaria** [comment]
Awesome reference! I'm gonna close this issue cause we're tracking progress on the main repo! Thanks!

**Comment by arielelkin** [comment]
? 

I'm confused.. Isn't this repo an autonomous component?

**Comment by paulofaria** [comment]
It is but we prefer aggregating all issues in the main repo so it's easier to maintain.
